# AdvancedMobControl by Ben12345rocks

# Debug levels:
# NONE
# INFO
# EXTRA
DebugLevel: NONE

# Valid Options:
# - FLAT
# - SQLITE
# - MYSQL
DataStorage: FLAT

# Information for mysql
MySQL:
  Host: ''
  # Default port is 3306
  Port: 3306 
  Database: ''
  Username: ''
  Password: ''
  # Max number of connections
  MaxConnections: 1
  # Wether or not to preload table
  # Increases performance greatly when using mysql
  # Set to false if you want multiple servers using the same table
  PreLoadTable: true

# Max number of mobs before money is 0
# Higher the number the more money players get
MaxMobs: 20

Format:
  # Message when player is given money for killing entity
  Money: 'You were given $%Money% for killing %Entity%'
  # Message when player is given money for killing entity via specific damage
  MoneyDamage: 'You were given $%Money% for killing %Entity% by %Damage%'
  # Message when player tries to run command without required permissions
  NoPerms: '&cYou do not have enough permission!'
  # Message when player types a command but does not input a number where needed
  NotNumber: '&cError on &6%arg%&c, number expected!'
  # CommandHandler help message
  HelpLine: '&3&l%Command% - &3%HelpMessage%'