name: AdvancedMobControl
version: 1.1
main: com.Ben12345rocks.AdvancedMobControl.Main
softdepend: [AdvancedCore]
commands:
  advancedmobcontrol:
    description: Plugin command
    aliases: [mobcontrol]